version: '3'

services:
 customers-service:
  container_name: customer-springboot
  build: .
  ports:
   - 8080:8080
  links:
   - mongo
 mongo:
  image: mongo
  container_name: customers-mongo
  ports:
   - 27017:27017
# volumes are not working for windows for docker. Hence commenting.  Need to uncomment for linux
#  volumes:
#   - ./data/db:/data/db